language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t saezbaldo/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true saezbaldo/react-test npm test

after_success:
  - docker build -t saezbaldo/multi-client ./client
  - docker build -t saezbaldo/multi-nginx ./nginx
  - docker build -t saezbaldo/multi-server ./server
  - docker build -t saezbaldo/multi-worker ./worker